### PR TITLE
Release binaries for s390x

### PR DESCRIPTION
**Pull request by namrata-ibm**
Looking forward to prebuilt s390x binary in future releases.

### CODE REVIEW

**Comment by namrata-ibm** [comment]
@jhump could you please have a look?

**Comment by namrata-ibm** [comment]
@jhump Could you please provide your feedback on this?

**Review by jhump — APPROVED** [review]

**Comment by jhump** [comment]
@namrata-ibm, sorry for the delay in looking at this. LGTM

**Comment by namrata-ibm** [comment]
Thank you @jhump .. Is there a release planned anytime soon?

**Comment by namrata-ibm** [comment]
@jhump There is another issue raised regarding Travis builds, #247 .. could you please check that as well?

**Comment by jhump** [comment]
> Thank you @jhump .. Is there a release planned anytime soon?

I'm afraid not. If you look at commits in the repo, you'll see our last release was about a month ago and there have been zero changes since then.

> @jhump There is another issue raised regarding Travis builds, #247 .. could you please check that as well?

Yes, I am painfully aware of that. I have been performing CI manually by checking out the branches and running `make ci`.

This isn't a super-high traffic repo at the moment, so it's not been very high priority to fix. But the plan is to move to Circle CI (which we are using for some other repos already, like fullstorydev/hauser).

**Comment by namrata-ibm** [comment]
> I'm afraid not. If you look at commits in the repo, you'll see our last release was about a month ago and there have been zero changes since then.
> 
Ok, we will look forward to it!
 
> Yes, I am painfully aware of that. I have been performing CI manually by checking out the branches and running `make ci`.
> 
> This isn't a super-high traffic repo at the moment, so it's not been very high priority to fix. But the plan is to move to Circle CI (which we are using for some other repos already, like fullstorydev/hauser).

Ohk, enabling Travis shouldn't be much of a hassle though, it is already on .com.. if adding more credits is a blocker then we can help. Please do let us know!

**Pull request merged**
