### PR TITLE
Added initial support for -t flag to show timings

### PR DESCRIPTION
**Pull request by KaibutsuX**
Shows very basic timing data for the Dial stage (TLS setup and BlockingDial) and InvokeRPC method as well as the total time.

### CODE REVIEW

**Review by dragonsinth — COMMENTED** [review]
Could we reduce the options by just making this part of `-vv`?  We could just log e.g. "start Dial" -> "end Dial (35ms)" in the places where this PR is capturing time.Now() and time.Since()

**Comment by dragonsinth** [comment]
How much are we talking about? I assumed this would be kinda coarse grained
timing on major steps.

**Comment by KaibutsuX** [comment]
I haven't dug into what further information I can get out of the connection, I assumed there might be finer grained details. But for now this at least gets me the information I was looking for to debug some slow responses from the a server. If you want this in -vv I can move it there.

**Comment by dragonsinth** [comment]
@KaibutsuX I pushed you a commit to clean this up a bit: WDYT?

**Review by dragonsinth — APPROVED** [review]

**Pull request merged**
