### PR TITLE
add Dockerfile to build grpcurl image

### PR DESCRIPTION
**Pull request by jkevlin**
Add a dockerfile to repo

### CODE REVIEW

**Comment by jhump** [comment]
@jkev53, thanks for the contribution. I am still discussing with colleagues how we want to support stuff like this -- Docker files and images, homebrew formulas, etc. For now, I'll leave this PR open and on hold.

**Comment by jhump** [comment]
@jkev53, is it okay if I close this PR? Thanks for this starting point, by the way. I've opened #104, which uses similar techniques, but goes a little further to try to shrink the size of the final image without sacrificing functionality. I hope to soon push these to a `fullstorydev` org in Docker Hub to make sure these images are easy for people to find. The first version I intend to push will be a v1.3.0 image.

**Comment by jkev53** [comment]
Sure, that's fine, hope it helped.
 
----- Original message -----From: Joshua Humphries <notifications@github.com>To: fullstorydev/grpcurl <grpcurl@noreply.github.com>Cc: John Kevlin <jkevlin@ibm.com>, Mention <mention@noreply.github.com>Subject: [EXTERNAL] Re: [fullstorydev/grpcurl] add Dockerfile to build grpcurl image (#65)Date: Wed, May 29, 2019 7:23 PM 
@jkev53, is it okay if I close this PR? Thanks for this starting point, by the way. I've opened #104, which uses similar techniques, but goes a little further to try to shrink the size of the final image without sacrificing functionality. I hope to soon push these to a fullstorydev org in Docker Hub to make sure these images are easy for people to find. The first version I intend to push will be a v1.3.0 image.

**Comment by jhump** [comment]
Superceded by #104.

**Pull request closed without merging**
